import {
  Run,
  AdCreative,
  RedditMention,
  GapOpportunity,
  ConceptIdea,
  Cluster,
  AppStoreResult,
  UGCAsset,
  UGCRecommendations,
} from '@/types';

export const mockRuns: Run[] = [
  {
    id: '1',
    projectId: 'proj-1',
    nicheQuery: 'AI watermark remover',
    seedTerms: ['watermark remover', 'remove watermark', 'watermark removal tool', 'AI image editor'],
    competitors: ['remove.bg', 'watermarkremover.io', 'apowersoft'],
    geo: 'US',
    status: 'complete',
    startedAt: new Date('2025-01-10T10:00:00'),
    finishedAt: new Date('2025-01-10T10:08:32'),
    scores: {
      saturation: 67,
      longevity: 78,
      dissatisfaction: 72,
      misalignment: 58,
      opportunity: 74,
      confidence: 0.82,
    },
  },
  {
    id: '2',
    projectId: 'proj-1',
    nicheQuery: 'Personal CRM app',
    seedTerms: ['personal crm', 'relationship manager', 'contact manager', 'networking app'],
    competitors: ['clay.earth', 'dex.app', 'monica.com'],
    geo: 'US',
    status: 'complete',
    startedAt: new Date('2025-01-12T14:00:00'),
    finishedAt: new Date('2025-01-12T14:07:15'),
    scores: {
      saturation: 45,
      longevity: 65,
      dissatisfaction: 81,
      misalignment: 73,
      opportunity: 82,
      confidence: 0.78,
    },
  },
  {
    id: '3',
    projectId: 'proj-1',
    nicheQuery: 'AI meeting notes',
    seedTerms: ['meeting notes', 'meeting transcription', 'ai notetaker', 'meeting summary'],
    competitors: ['otter.ai', 'fireflies.ai', 'grain.com'],
    geo: 'US',
    status: 'running',
    startedAt: new Date('2025-01-13T22:00:00'),
    scores: {
      saturation: 0,
      longevity: 0,
      dissatisfaction: 0,
      misalignment: 0,
      opportunity: 0,
      confidence: 0,
    },
  },
];

export const mockAdCreatives: AdCreative[] = [
  {
    id: 'ad-1',
    runId: '1',
    source: 'meta',
    advertiserName: 'WatermarkRemover Pro',
    creativeText: 'Remove watermarks from any image in seconds! AI-powered, no signup required. Try free now.',
    headline: 'Remove Watermarks Instantly',
    cta: 'Try Free',
    landingUrl: 'https://watermarkremoverpro.com',
    firstSeen: new Date('2024-08-15'),
    lastSeen: new Date('2025-01-13'),
    isActive: true,
    mediaType: 'video',
    daysRunning: 151,
  },
  {
    id: 'ad-2',
    runId: '1',
    source: 'meta',
    advertiserName: 'CleanImage AI',
    creativeText: 'Tired of ugly watermarks? Our AI removes them perfectly. 100% free, unlimited usage.',
    headline: 'Free Watermark Removal',
    cta: 'Remove Now',
    landingUrl: 'https://cleanimage.ai',
    firstSeen: new Date('2024-10-01'),
    lastSeen: new Date('2025-01-13'),
    isActive: true,
    mediaType: 'image',
    daysRunning: 104,
  },
  {
    id: 'ad-3',
    runId: '1',
    source: 'google',
    advertiserName: 'EasyRemove',
    creativeText: 'Professional watermark removal tool. Batch processing available. Start your free trial.',
    headline: 'Batch Watermark Removal',
    cta: 'Start Free Trial',
    landingUrl: 'https://easyremove.io',
    firstSeen: new Date('2024-11-20'),
    lastSeen: new Date('2025-01-10'),
    isActive: true,
    mediaType: 'image',
    daysRunning: 51,
  },
  {
    id: 'ad-4',
    runId: '1',
    source: 'meta',
    advertiserName: 'PixelPerfect',
    creativeText: 'Remove watermarks without losing quality. AI preserves every detail. See the difference.',
    headline: 'Quality Preserved',
    cta: 'See Demo',
    landingUrl: 'https://pixelperfect.app',
    firstSeen: new Date('2024-06-10'),
    lastSeen: new Date('2025-01-13'),
    isActive: true,
    mediaType: 'video',
    daysRunning: 217,
  },
];

export const mockRedditMentions: RedditMention[] = [
  {
    id: 'reddit-1',
    runId: '1',
    subreddit: 'r/graphic_design',
    type: 'post',
    title: 'Best watermark remover that actually works?',
    text: 'I\'ve tried like 5 different tools and they all leave artifacts or blur the edges. Anyone found one that actually preserves quality?',
    score: 234,
    numComments: 89,
    createdAt: new Date('2025-01-08'),
    permalink: '/r/graphic_design/comments/xyz123',
    matchedEntities: ['watermark remover'],
  },
  {
    id: 'reddit-2',
    runId: '1',
    subreddit: 'r/photography',
    type: 'comment',
    text: 'Most of these "AI removers" are scams. They charge $20/month and the results are garbage. The free ones are actually better sometimes.',
    score: 156,
    createdAt: new Date('2025-01-05'),
    permalink: '/r/photography/comments/abc456/comment/def789',
    matchedEntities: ['AI removers', 'watermark'],
  },
  {
    id: 'reddit-3',
    runId: '1',
    subreddit: 'r/editors',
    type: 'post',
    title: 'Why do watermark removers destroy the edges?',
    text: 'Every single one I\'ve used leaves a halo effect around where the watermark was. Is this a fundamental limitation or are these tools just bad?',
    score: 187,
    numComments: 67,
    createdAt: new Date('2025-01-02'),
    permalink: '/r/editors/comments/ghi789',
    matchedEntities: ['watermark removers'],
  },
  {
    id: 'reddit-4',
    runId: '1',
    subreddit: 'r/software',
    type: 'comment',
    text: 'Pricing on these tools is insane. They want $10/image or $30/month. For something that\'s basically one AI model call? Highway robbery.',
    score: 298,
    createdAt: new Date('2025-01-10'),
    permalink: '/r/software/comments/jkl012/comment/mno345',
    matchedEntities: ['watermark', 'pricing'],
  },
];

export const mockClusters: Cluster[] = [
  {
    id: 'cluster-1',
    runId: '1',
    clusterType: 'objection',
    label: 'Poor edge quality / artifacts',
    examples: [
      { id: 'reddit-1', snippet: 'they all leave artifacts or blur the edges' },
      { id: 'reddit-3', snippet: 'leaves a halo effect around where the watermark was' },
    ],
    frequency: 47,
    intensity: 0.85,
  },
  {
    id: 'cluster-2',
    runId: '1',
    clusterType: 'objection',
    label: 'Overpriced / pricing friction',
    examples: [
      { id: 'reddit-2', snippet: 'They charge $20/month and the results are garbage' },
      { id: 'reddit-4', snippet: 'They want $10/image or $30/month' },
    ],
    frequency: 38,
    intensity: 0.78,
  },
  {
    id: 'cluster-3',
    runId: '1',
    clusterType: 'angle',
    label: 'Speed / Instant results',
    examples: [
      { id: 'ad-1', snippet: 'Remove watermarks from any image in seconds' },
      { id: 'ad-2', snippet: 'removes them perfectly' },
    ],
    frequency: 62,
    intensity: 0.72,
  },
  {
    id: 'cluster-4',
    runId: '1',
    clusterType: 'feature',
    label: 'Batch processing',
    examples: [
      { id: 'ad-3', snippet: 'Batch processing available' },
    ],
    frequency: 23,
    intensity: 0.65,
  },
];

export const mockGapOpportunities: GapOpportunity[] = [
  {
    id: 'gap-1',
    runId: '1',
    gapType: 'product',
    title: 'Edge quality is the #1 complaint but no ads address it',
    problem: 'Users consistently complain about artifacts and blurred edges after watermark removal, but advertisers focus on speed and price instead of quality.',
    evidenceAds: [
      { id: 'ad-1', snippet: 'Remove watermarks from any image in seconds' },
      { id: 'ad-2', snippet: '100% free, unlimited usage' },
    ],
    evidenceReddit: [
      { id: 'reddit-1', snippet: 'they all leave artifacts or blur the edges' },
      { id: 'reddit-3', snippet: 'leaves a halo effect around where the watermark was' },
    ],
    recommendation: 'Build "edge-preserve mode" as a core differentiator. Lead ads with "Clean edges guaranteed" + before/after comparisons showing edge quality.',
    opportunityScore: 89,
    confidence: 0.87,
  },
  {
    id: 'gap-2',
    runId: '1',
    gapType: 'pricing',
    title: 'Pricing feels like a scam - transparency gap',
    problem: 'Users feel subscription pricing is exploitative for a simple tool. Ads hide pricing until deep in funnel.',
    evidenceAds: [
      { id: 'ad-1', snippet: 'Try free now' },
      { id: 'ad-3', snippet: 'Start your free trial' },
    ],
    evidenceReddit: [
      { id: 'reddit-2', snippet: 'They charge $20/month and the results are garbage' },
      { id: 'reddit-4', snippet: 'They want $10/image or $30/month' },
    ],
    recommendation: 'Show transparent pricing in ads. Consider one-time payment or generous free tier (10 images/month). Lead with "No subscription required."',
    opportunityScore: 76,
    confidence: 0.82,
  },
  {
    id: 'gap-3',
    runId: '1',
    gapType: 'trust',
    title: 'No proof of quality in ads',
    problem: 'Ads claim quality but never show actual results. Users are skeptical because they\'ve been burned before.',
    evidenceAds: [
      { id: 'ad-4', snippet: 'AI preserves every detail' },
    ],
    evidenceReddit: [
      { id: 'reddit-2', snippet: 'Most of these "AI removers" are scams' },
    ],
    recommendation: 'Show real before/after examples in every ad. Include edge close-ups. Add "zoom in" demonstration videos.',
    opportunityScore: 72,
    confidence: 0.79,
  },
];

export const mockConceptIdeas: ConceptIdea[] = [
  {
    id: 'concept-1',
    runId: '1',
    name: 'EdgeGuard Watermark Remover',
    oneLiner: 'The only watermark remover that guarantees clean edges - or your money back.',
    platformRecommendation: 'web',
    platformReasoning: 'Web allows faster iteration on AI model improvements. Users upload images anyway - no native mobile features needed. SEO can capture high-intent search traffic.',
    industry: 'Image Editing / Creative Tools',
    icp: 'Freelance designers, social media managers, content creators who need to quickly clean images',
    businessModel: 'b2c',
    gapThesis: 'Every competitor focuses on speed and price. None address the #1 user complaint: edge artifacts. Win by being the "quality-first" option.',
    mvpSpec: {
      mustHaves: [
        'Edge-preserve AI model (fine-tuned on edge cases)',
        'Before/after slider with zoom',
        'Transparent pricing on landing page',
        '10 free images/month, then $5/50 images',
        'Batch upload (up to 10)',
      ],
      nonGoals: [
        'Mobile app (v2)',
        'API access (v2)',
        'Team features',
        'Background removal (different product)',
      ],
      differentiator: 'Edge quality score shown before/after processing',
      pricingModel: 'Credits-based, no subscription',
      successCriteria: [
        '< 3% refund rate on edge quality complaints',
        '40%+ return user rate within 30 days',
        'CAC < $8 on Meta ads',
      ],
    },
    metrics: {
      cpcLow: 0.45,
      cpcExpected: 0.72,
      cpcHigh: 1.20,
      cacLow: 4.50,
      cacExpected: 7.20,
      cacHigh: 12.00,
      tamLow: 150000000,
      tamExpected: 280000000,
      tamHigh: 450000000,
      implementationDifficulty: 42,
      humanTouchLevel: 'low',
      autonomousSuitability: 'high',
      buildDifficulty: 38,
      distributionDifficulty: 55,
      opportunityScore: 84,
      confidence: 0.81,
    },
  },
  {
    id: 'concept-2',
    runId: '1',
    name: 'BatchMark Pro',
    oneLiner: 'Watermark removal for teams - process 1000s of images with consistent quality.',
    platformRecommendation: 'web',
    platformReasoning: 'B2B use case requires desktop workflows, integrations, and team management. Web-first with potential desktop app later.',
    industry: 'Enterprise Image Processing',
    icp: 'Marketing agencies, e-commerce teams, stock photo companies',
    businessModel: 'b2b',
    gapThesis: 'Current tools are consumer-focused. No one addresses batch processing with quality controls and team collaboration.',
    mvpSpec: {
      mustHaves: [
        'Bulk upload (100+ images)',
        'Quality threshold settings',
        'Team workspaces',
        'Processing queue with progress',
        'Export to cloud storage (S3, GCS)',
      ],
      nonGoals: [
        'Consumer pricing',
        'Mobile app',
        'Real-time processing',
      ],
      differentiator: 'Quality control dashboard showing per-image confidence scores',
      pricingModel: 'Per-seat subscription: $49/seat/month',
      successCriteria: [
        'Land 3 agency pilots in month 1',
        '> 80% pilot conversion to paid',
        'NPS > 40',
      ],
    },
    metrics: {
      cpcLow: 2.50,
      cpcExpected: 4.20,
      cpcHigh: 7.80,
      cacLow: 180,
      cacExpected: 320,
      cacHigh: 580,
      tamLow: 80000000,
      tamExpected: 150000000,
      tamHigh: 280000000,
      implementationDifficulty: 65,
      humanTouchLevel: 'medium',
      autonomousSuitability: 'medium',
      buildDifficulty: 58,
      distributionDifficulty: 48,
      opportunityScore: 71,
      confidence: 0.74,
    },
  },
];

export const mockAppStoreResults: AppStoreResult[] = [
  {
    id: 'app-1',
    runId: '1',
    platform: 'ios',
    appName: 'Watermark Remover - Photo Edit',
    appId: '1234567890',
    developer: 'Photo Tools Inc',
    rating: 4.2,
    reviewCount: 12453,
    description: 'Remove watermarks from photos easily with AI technology.',
    category: 'Photo & Video',
    price: 'Free with IAP',
  },
  {
    id: 'app-2',
    runId: '1',
    platform: 'ios',
    appName: 'Remove Watermark - Retouch',
    appId: '0987654321',
    developer: 'Retouch Labs',
    rating: 3.8,
    reviewCount: 8234,
    description: 'Professional watermark removal and photo retouching.',
    category: 'Photo & Video',
    price: '$4.99',
  },
  {
    id: 'app-3',
    runId: '1',
    platform: 'android',
    appName: 'Watermark Remover & Editor',
    appId: 'com.watermark.remover',
    developer: 'AI Photo Studio',
    rating: 4.0,
    reviewCount: 45623,
    description: 'Remove watermarks from any image using advanced AI.',
    category: 'Photography',
    price: 'Free with Ads',
  },
  {
    id: 'app-4',
    runId: '1',
    platform: 'web',
    appName: 'WatermarkRemover.io',
    appId: 'watermarkremover.io',
    developer: 'WR Tools Ltd',
    rating: 4.5,
    reviewCount: 2341,
    description: 'Online watermark removal tool. No download required.',
    category: 'Online Tool',
    price: '$9.99/mo',
  },
];

export const mockUGCAssets: UGCAsset[] = [
  {
    id: 'ugc-1',
    runId: '1',
    source: 'tiktok_top_ads',
    platform: 'tiktok',
    url: 'https://tiktok.com/@example/video/1',
    thumbnailUrl: '/placeholder-ugc-1.jpg',
    caption: 'POV: You finally found a watermark remover that actually works 🤯',
    createdAt: new Date('2025-01-05'),
    metrics: {
      views: 2450000,
      likes: 189000,
      comments: 4500,
      shares: 23000,
      reachUniqueUsers: 1800000,
      firstShown: new Date('2024-11-15'),
      lastShown: new Date('2025-01-13'),
      score: 92,
    },
    patterns: {
      hookType: 'POV / Relatable',
      format: 'Screen recording demo',
      proofType: 'Before/after comparison',
      objectionHandled: 'Quality concerns',
      ctaStyle: 'Link in bio',
      confidence: 0.89,
    },
  },
  {
    id: 'ugc-2',
    runId: '1',
    source: 'tiktok_top_ads',
    platform: 'tiktok',
    url: 'https://tiktok.com/@example/video/2',
    thumbnailUrl: '/placeholder-ugc-2.jpg',
    caption: 'Stop paying $20/month for watermark removal. Here\'s what I use instead...',
    createdAt: new Date('2025-01-08'),
    metrics: {
      views: 1890000,
      likes: 145000,
      comments: 3200,
      shares: 18000,
      reachUniqueUsers: 1400000,
      firstShown: new Date('2024-12-01'),
      lastShown: new Date('2025-01-13'),
      score: 87,
    },
    patterns: {
      hookType: 'Pain point callout',
      format: 'Talking head + demo',
      proofType: 'Price comparison',
      objectionHandled: 'Pricing concerns',
      ctaStyle: 'Comment "link"',
      confidence: 0.92,
    },
  },
  {
    id: 'ugc-3',
    runId: '1',
    source: 'tiktok_trend',
    platform: 'tiktok',
    url: 'https://tiktok.com/@example/video/3',
    thumbnailUrl: '/placeholder-ugc-3.jpg',
    caption: 'Designer hack: remove watermarks in 3 seconds',
    createdAt: new Date('2025-01-10'),
    metrics: {
      views: 890000,
      likes: 67000,
      comments: 1500,
      shares: 8900,
      score: 78,
    },
    patterns: {
      hookType: 'Hack / Life tip',
      format: 'Quick tutorial',
      proofType: 'Speed demonstration',
      ctaStyle: 'Follow for more',
      confidence: 0.85,
    },
  },
];

export const mockUGCRecommendations: UGCRecommendations = {
  id: 'ugc-rec-1',
  runId: '1',
  hooks: [
    { text: 'POV: You finally found a watermark remover that doesn\'t destroy the edges', type: 'POV / Relatable' },
    { text: 'Stop wasting money on watermark tools that don\'t work', type: 'Pain point callout' },
    { text: 'The watermark remover that designers are gatekeeping', type: 'Curiosity / FOMO' },
    { text: 'I tested 10 watermark removers so you don\'t have to', type: 'Authority / Research' },
    { text: 'Why every "free" watermark remover is actually a scam', type: 'Myth bust' },
    { text: 'This AI removes watermarks WITHOUT blurring the edges', type: 'Feature highlight' },
    { text: 'Designer hack that will save you hours every week', type: 'Hack / Productivity' },
    { text: 'The tool I use when clients send me watermarked images', type: 'Use case / Scenario' },
    { text: 'Free watermark removal that actually looks professional', type: 'Value proposition' },
    { text: 'Before you pay for another watermark tool, watch this', type: 'Warning / Save money' },
  ],
  scripts: [
    {
      duration: '15s',
      outline: [
        '0-3s: Hook - "POV: You found a watermark remover that works"',
        '3-10s: Demo - Show before/after with edge zoom',
        '10-15s: CTA - "Link in bio, first 10 images free"',
      ],
    },
    {
      duration: '30s',
      outline: [
        '0-5s: Hook - "I tested 10 watermark removers"',
        '5-15s: Problem - Show 3 tools with bad results (blur, artifacts)',
        '15-25s: Solution - Demo your tool with clean edges',
        '25-30s: CTA - "Comment LINK and I\'ll send it to you"',
      ],
    },
    {
      duration: '45s',
      outline: [
        '0-5s: Hook - "Stop paying $20/month for watermark removal"',
        '5-15s: Establish credibility - "As a designer, I remove watermarks daily"',
        '15-25s: Compare pricing - Show competitor pricing vs yours',
        '25-40s: Demo - Full workflow with before/after',
        '40-45s: CTA - "Link in bio, no subscription needed"',
      ],
    },
  ],
  shotList: [
    { shot: 'Screen recording: Upload watermarked image', notes: 'Show drag-and-drop, emphasize simplicity' },
    { shot: 'Screen recording: Processing with progress bar', notes: 'Keep brief, 2-3 seconds max' },
    { shot: 'Split screen: Before/after with edge zoom', notes: 'This is the money shot - linger here' },
    { shot: 'Face cam reaction (optional)', notes: 'Genuine surprise/satisfaction works best' },
    { shot: 'Screen recording: Download result', notes: 'Show file quality/size if impressive' },
    { shot: 'Competitor comparison (optional)', notes: 'Show blurry edges from other tools' },
  ],
  angleMap: [
    { angle: 'Edge quality focus', priority: 'high', reasoning: 'Direct response to #1 objection. No competitors addressing this.' },
    { angle: 'Transparent pricing', priority: 'high', reasoning: 'Major pain point in Reddit data. Low-hanging fruit.' },
    { angle: 'Speed/convenience', priority: 'medium', reasoning: 'Everyone claims this - need differentiation.' },
    { angle: 'Batch processing', priority: 'medium', reasoning: 'Appeals to power users. Less saturated angle.' },
    { angle: 'Free tier generous', priority: 'low', reasoning: 'Generic angle, but worth testing against pricing-focused hooks.' },
  ],
};
