-- Subscription Usage Tracking (BILL-009)
-- Note: subscription_usage table and policies already exist from earlier migration (20260116000001)
-- This migration is intentionally empty to avoid conflicts
